### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by hendrixcosta** [kmee/kmee_odoo_addons#34]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

# Modules to migrate

- [ ] account_payment_due_list
- [ ] account_payment_move_line
- [ ] calendar_invite_2_user
- [ ] call_log_date
- [ ] commission_report_with_sale_order
- [ ] kmee_account_move_line_filter
- [ ] l10n_br_hr_payroll_report
- [ ] l10n_br_stock_multicompany_resupply
- [ ] sale_item_count
